baseURL = "https://www.tomshanley.co.nz/"
languageCode = "en-us"
title = "Tom Shanley Data Viz Christchurch NZ"
theme = "hugo-icon"

# Metadata
[params]
  author = "Tom Shanley"
  description = "Cool description"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.png"
  title = "I &hearts; data visualistion"
  description = "Use your data to explore, understand and explain"

# Navigation section
[params.nav]
  mission = "Hello!"
  services = "Services"
  team = "About me"
  # contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Marketing"
    subtitle = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptate laborum sapiente officiis molestiaea."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos aspernatur eius doloremque ad, eaque pariatur, repellendus illum, nostrum velit necessitatibus molestias.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "Resources"
    subtitle = "Quam quasi illum expedita dicta nemo fugit reprehenderit similique! Corporis praesentium magnam sequi."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum. Sunt saepe ut, explicabo consectetur, nostrum illo est.</p><ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Strategy"
    subtitle = "Magnam iste obcaecati illo laboriosam amet. Dignissimos sed quis voluptatum corporis adipisci amet."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore illum expedita placeat debitis, dignissimos obcaecati et modi. Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul>"

# Services section
[params.services]
  enable = true
  video = false
  title = "What I can do for you"
  # description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-present"
    title = "Consult"
    description = "I will work with you and your team to understand what you are trying to achieve, your data sources and analysis, so that we can design and build the best data visualisations for your context."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Review"
    description = "I can review your existing data visualisations (reports, presentations, web) and provide recommendations for potential improvements and enhancements."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Design"
    description = "I can work with the data tools and branding guidelines that are available to you, to develop the design specifications and solutions for review and implementation, by your designers or analysts, or by me. I work hard to make sure the designs allow your audiences to understand, explore and engage with your data."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Build"
    description = "I can deliver final products where called upon for print, analytic tools and web. I can work with your applications of choice, such as D3.JS, R (including ggplot2), Tableau, Kumu and GIS tools, as well as the Adobe and Microsoft suites."

  [[params.services.item]]
    icon = "icon-support"
    title = "Embed"
    description = "Often the data visualisations we produce need to be reused – monthly reports, presentation templates. I can work with your team to ensure that the pipeline from data, analysis, design and presentation is efficient and effective."

# Work section
[params.work]
  enable = true
  title = "Previous clients"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = false
  title = "About me"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.team.item]]
    name = "Jean Doe"
    position = "Chief legend"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person1.jpg"
    email = "#"
    telephone = "#"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"
    linkedin = "#"
    whatsapp = "#"


# Contact section
[params.contact]
  enable = false
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  note = "<p><small>This website is built using Netlify and Hugo <br> The website uses the Free HTML5 Hugo Template &copy; 2016 All Rights Reserved <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> + Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  github = "https://www.github.com/tomshanley"
  twitter = "https://www.twitter.com/tomshanleynz"
  linkedin = "#"
  pinterest = "https://nz.pinterest.com/tomshanley/data-visualisation/"







