# Main config file for icon theme.
baseURL = "https://www.tomshanley.co.nz/"
languageCode = "en-nz"
title = "Tom Shanley Data Visualisation + Business Analysis @ Christchurch NZ"
theme = "hugo-icon"

# Metadata
[params]
  author = "Tom Shanley"
  description = "Data visualisation consultant and business analyst - Christchurch, New Zealand"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.png"
  title = "I &hearts; data visualistion"
  description = "My name is Tom Shanley. I can help you use your data to explore, understand and explain"

# Navigation section
[params.nav]
  mission = "Our Mission"
  services = "Services"
  work = "Previous clients"
  team = "About"
  contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = false

# Services section
[params.services]
  enable = true
  video = false
  title = "What I can do for you"

  [[params.services.item]]
    icon = "icon-present"
    title = "Consult"
    description = "Work with your team to understand your goals, data and analysis"

  [[params.services.item]]
    icon = "icon-eye"
    title = "Review"
    description = "Review your existing data visualisations, recommend improvements and steps to achievin"

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Design"
    description = "Design specifications and solutions specfic to your tools and branding guidelines"

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Build"
    description = "Develop and deliver the final products for print, analytical tools and web"

    [[params.services.item]]
    icon = "icon-support"
    title = "Embed"
    description = "Develop the ongoing processes for maintaining and reusing the visualisations, from data gathering through to presentation"
    
  [[params.services.item]]
    icon = "icon-support"
    title = "Business analysis"
    description = "Data visualisations to support your business analysis and project"

  



# Team section
[params.team]
  enable = true
  title = "Nice to meet you"

  [[params.team.item]]
    description = "I live and work in Christchurch, New Zealand. Originally from the UK, I am a business analyst with a particular passion for presenting data and complex information. I have over 10 years experience working in IT and government, and enjoy the challenge of analysing and presenting the complex environments in which we work. I work with [Redvespa](https://www.redvespa.com) - please contact them if you require business analysis services, or would like to see how I may help your business with visualising your data."
    img = "images/person1.jpg"
    github = "https://www.github.com/tomshanley"
    twitter = "https://www.twitter.com/tomshanleynz"
    linkedin = "#"
    pinterest = "https://nz.pinterest.com/tomshanley/data-visualisation/"


# Work section
[params.work]
  enable = true
  title = "Some of my previous clients"

  [[params.work.item]]
    title = "Department of Internal Affairs"
    subtitle = "interactive network visualisation of government services, agencies and customer life events"
    img = "images/dia.jpg"

  [[params.work.item]]
    title = "Social Investment Agency"
    subtitle = "design and development of print and online interactive visualisations"
    img = "images/sia.jpg"

  [[params.work.item]]
    title = "Ministry of Social Development"
    subtitle = " design and development of monthly reporting dashboards"
    img = "images/msd.jpg"

  [[params.work.item]]
    title = "Ministry of Education"
    subtitle = "design and development of data visualisations and infographics"
    img = "images/moe.jpg"

  [[params.work.item]]
    title = "LINZ"
    subtitle = "real-time operational dashboard requirements"
    img = "images/linz.jpg"

  [[params.work.item]]
    title = "Superu"
    subtitle = "consultancy and design of visualisations for research publications "
    img = "images/superu.jpg"

  [[params.work.item]]
    title = "Sankey Plugin"
    subtitle = "development of a D3 plugin to visualisation circular directional networks"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Redvespa"
    subtitle = "design and implementation of business intelligence reporting"
    img = "images/redvespa.png"

# Contact section
[params.contact]
  enable = false
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>This website is built using <a href='https://www.netlify.com/'>Netlify</a> and <a href='https://gohugo.io/'>Hugo</a> <br> The website uses the Free HTML5 Hugo Template &copy; 2016 All Rights Reserved <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> + Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  github = "https://www.github.com/tomshanley"
  twitter = "https://www.twitter.com/tomshanleynz"
  linkedin = "#"
  pinterest = "https://nz.pinterest.com/tomshanley/data-visualisation/"
  