baseURL       = "https://www.tomshanley.co.nz/"
languageCode  = "en-us"
title         = "Tom Shanley | Data Viz + Business Analysis"
theme         = "roxo-tom"
summarylength = 25

[markup.goldmark.renderer] 
  unsafe= true

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 2
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 3
  
  #[[menu.nav]]
  #  name    = "Blog"
  #  url     = "blog"
  #  weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  # googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  # formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = false
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.png"
    heading               = "I love data visualisation"
    #tagline               = "DATA + ANALYSIS"
    primary_button        = "My work"
    primary_button_url    = "portfolio"
    secondary_button      = "About me"
    secondary_button_url  = "about"

  [params.portfolio]
    enable    = true
    title     = "SOME OF MY PREVIOUS WORK"
    subtitle  = "I like to build visualisations, and the tools for communitiy to do the same..."
    Paginate = 4

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
     # title   = "Contact Info:"
     # email   = "tomshanleydataviz@gmail.com"
     # address = "713 Elmwood St.<br>Prior Lake, MN 55372"
     # phone   = "409-896-1444"
     
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap:"
        [[params.footer.sitemap.link]]
          name = "About me"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      #  [[params.footer.sitemap.link]]
      #    name = "Blog"
      #    url  = "blog"
      #  [[params.footer.sitemap.link]]
      #    name = "Contact"
      #    url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Find me on:"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/tomshanleynz"
        [[params.footer.social.link]]
          name = "Github"
          url  = "https://www.github.com/tomshanley"
        [[params.footer.social.link]]
          name = "Observable"
          url  = "https://observablehq.com/@tomshanley"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "https://www.linkedin.com/in/tshanley/"
       # [[params.footer.social.link]]
       #   name = "Instagram"
       #   url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "I can help you:"
        description = "to better understand <br>and present your data,<br>and have some fun along the way"